openapi: 3.0.3
info:
  title: ONDC Mock Server - OpenAPI 3.0
  description: >-
    This is a Mock Server for integrating with ONDC. Currently, it supports B2B.
    An easy way to get started would be to ask yourself the two question -
    _"which network participant am I going to send to?"_ and _"what would be the
    action/on_action I am going to send?"_. With these you can easily construct
    the URL you need to mock and then find that among this list. <br />
  contact:
    email: team@ondc.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about ONDC
  url: https://ondc.org
tags:
  - name: B2B
    description: Everything for B2B domain
    externalDocs:
      description: Find out more
      url: >-
        https://github.com/ONDC-Official/ONDC-RET-Specifications/tree/release-2.0.2
  - name: Auth
    description: Endpoints for Authentication
paths:
  /api/auth/signCheck:
    post:
      tags:
        - Auth
      summary: Check the validity of a authorization token
      # parameters:
      #   - name: authorization
      #     in: header
      #     description: Signed Authorization Header
      #     required: true
      #     type: string
      security:
        - ApiKeyAuth: []
      requestBody:
        description: Request Body should contain the log which is signed.
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Request Body should contain the log which is signed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_check_response'
           
  /api/b2b/bpp/search:
    post:
      tags:
        - B2B
      summary: Mock search request to BPP
      requestBody:
        description: Search Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Search.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/select:
    post:
      tags:
        - B2B
      summary: Mock select request to BPP
      requestBody:
        description: Select Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Select.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/init:
    post:
      tags:
        - B2B
      summary: Mock init request to BPP
      requestBody:
        description: Init Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Init.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/confirm:
    post:
      tags:
        - B2B
      summary: Mock confirm request to BPP
      requestBody:
        description: confirm Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Confirm.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/update-fulfillment:
    post:
      tags:
        - B2B
      summary: Mock update fulfillment request to BPP
      requestBody:
        description: update fulfillment Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Update.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/update-prepaid:
    post:
      tags:
        - B2B
      summary: Mock update prepaid request to BPPs
      requestBody:
        description: update prepaid Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Update.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/status-delivered:
    post:
      tags:
        - B2B
      summary: Mock status delivered request to BPP
      requestBody:
        description: status delivered Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Status.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/status-out-for-delivery:
    post:
      tags:
        - B2B
      summary: Mock status out for delivery request to BPP
      requestBody:
        description: status out for delivery Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Status.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/status-picked-up:
    post:
      tags:
        - B2B
      summary: Mock status picked up request to BPP
      requestBody:
        description: status picked up Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Status.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bpp/status-proforma-invoice:
    post:
      tags:
        - B2B
      summary: Mock status proforma invoice request to BPP
      requestBody:
        description: status proforma invoice Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Status.yaml
      responses:
        '200':
          description: Successfull response from BPP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bap/onSearch:
    post:
      tags:
        - B2B
      summary: Mock on search request to BAP
      requestBody:
        description: On Search Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnSearch.yaml
      responses:
        '200':
          description: Successfull response from BAP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bap/onInit:
    post:
      tags:
        - B2B
      summary: Mock on init request to BAP
      requestBody:
        description: On Init Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnInit.yaml
      responses:
        '200':
          description: Successfull response from BAP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bap/onSelect:
    post:
      tags:
        - B2B
      summary: Mock on select request to BAP
      requestBody:
        description: On Select Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnSelect.yaml
      responses:
        '200':
          description: Successfull response from BAP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bap/onConfirm:
    post:
      tags:
        - B2B
      summary: Mock on confirm request to BAP
      requestBody:
        description: On Confirm Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnConfirm.yaml
      responses:
        '200':
          description: Successfull response from BAP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bap/onUpdate:
    post:
      tags:
        - B2B
      summary: Mock on update request to BAP
      requestBody:
        description: On Update Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnUpdate.yaml
      responses:
        '200':
          description: Successfull response from BAP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /api/b2b/bap/onStatus:
    post:
      tags:
        - B2B
      summary: Mock on status request to BAP
      requestBody:
        description: On Status Request Log
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnStatus.yaml
      responses:
        '200':
          description: Successfull response from BAP
          content:
            application/json:
              schema:
                $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: authorization  # name of the header, query parameter or cookie
  schemas:
    auth_check_response:
      type: object
      properties:
        message:
          type: string
          example: "Valid Signature"

security:
  - ApiKeyAuth: [] 